name: fff_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  clock: ^1.1.2
  figma_squircle: ^0.6.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.3
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  package_info_plus: ^9.0.0
  riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  simple_logger: ^1.10.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  build_runner: ^2.7.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Noto_Sans_JP/
    - assets/fonts/Noto_Sans_JP/static/
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Black.ttf
          weight: 900